#! /bin/sh

# startup applications
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -curson_name left_ptr
$HOME/.config/polybar/launch.sh
picom -b
feh --bg-fill -z $HOME/Pictures/wallpapers/
# wal -i $HOME/Pictures/wallpapers/
# nitrogen --restore
dunst &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d ' ' ' ' ' ' ' ' ' ' '󰙯 ' ' ' ' '


bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.52

bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config paddingless_monocle  true
bspc config focus_follows_pointer true


# workspace rules
bspc rule -a Alacritty desktop='^1' follow=on

bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a brave-browser desktop='^2' follow=on focus=on


bspc rule -a code desktop='^3' follow=on focus=on

bspc rule -a Thunar desktop='^4' follow=on focus=on
bspc rule -a desktop='^4' follow=on focus=on

bspc rule -a vlc desktop='^5' follow=on focus=on

bspc rule -a discord desktop='^6' follow=on focus=on

bspc rule -a spotify desktop='^7' follow=on focus=on
bspc rule -a libreoffice-* desktop='^8' follow=on focus=on

# special rules
bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mplayer2 state=floating

